name: Clemens Frede
favicon: null
layout_spectrum: 0.94937
typography_spectrum: 0.82705
title: Hang with me.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffaf7'
    - '#a2b2af'
    - '#b3bfbc'
  brandStrength: 0.2191489
  lightness: 0.6531915
  saturation: 0.5212766
  rhythmicContrast: 0.506383
purpose: []
