name: Clemens Frede
favicon: null
layout_spectrum: 0.94937
typography_spectrum: 0.82705
title: Hang with me.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffaf7'
    - '#a2b2af'
    - '#b3bfbc'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
