title: Hang with me.
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.5382979
favicon: null
name: Clemens Frede
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.2191489
  lightness: 0.75
  saturation: 0.2521079
  rhythmicContrast: 0.1593592
  brandColors:
    - '#fffaf7'
    - '#a2b2af'
    - '#b3bfbc'
typography_spectrum: 0.82705
