name: Clemens Frede
favicon: null
layout_spectrum: 0.94937
typography_spectrum: 0.82705
title: Hang with me.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffaf7'
    - '#a2b2af'
    - '#252910'
    - '#5b6823'
    - '#8d9446'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
