title: Hang with me.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5212766
  brandStrength: 0.2191489
  lightness: 0.6531915
  brandColors:
    - '#fffaf7'
    - '#a2b2af'
    - '#252910'
    - '#5b6823'
    - '#8d9446'
  rhythmicContrast: 0.506383
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Clemens Frede
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.82705
layout_spectrum: 0.94937
