name: Clemens Frede
favicon: null
layout_spectrum: 0.30102542811073363
typography_spectrum: 0.6841916716657579
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.26666019880212843
  lightness: 0.6375909405760467
  saturation: 0.7290212705265731
  rhythmicContrast: 0.5449717123992741
purpose: []
