name: Clemens Frede
favicon: null
layout_spectrum: 0.18381
typography_spectrum: 0.82705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffaf7'
    - '#a2b2af'
    - '#252910'
    - '#5b6823'
    - '#8d9446'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.7290212705265731
  rhythmicContrast: 0.25
purpose: []
